routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin','middleware' => ['web', 'auth:admin']], function() {
    Route::get('/', function () {
        return view('admin.welcome');
    });

    Route::resource('betting-location', 'Admin\BettingLocationController', ['as' => 'admin']);
    Route::resource('user', 'Admin\UserController', ['as' => 'admin'] );
    Route::resource('player', 'Admin\PlayerController', ['as' => 'admin'] );
    Route::resource('lucky6/ticket', 'Admin\Lucky6TicketController', ['except' => ['destroy', 'edit', 'update'],'as' => 'admin.lucky6']);
    Route::get('lucky6/statistic', ['uses' => 'Admin\Lucky6TicketController@statistic','as' => 'admin.lucky6.statistic']);
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'player', 'middleware' => ['web', 'auth:web']], function() {

    Route::get('/', function () {
        return view('player.welcome');
    });

    Route::resource('lucky6/ticket', 'Player\Lucky6TicketController', ['as' => 'player.lucky6']);
});

app/Models/BettingLocation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BettingLocation extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'name',
        'admin_user_id'
    ];

    public function adminLocation()
    {
        return $this->belongsTo(AdminUser::class, 'admin_user_id');
    }

    public function scopeCriteriaByAdminLocation($query, $adminUserId = null)
    {
        if($adminUserId) {
            return $query->where('admin_user_id', $adminUserId);
        }
    }
}

app/Http/Controllers/Admin/BettingLocationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\BettingLocation\CreateBettingLocationRequest;
use App\Models\BettingLocation;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BettingLocationController extends Controller
{
    public function index(Request $request)
    {
        $bettingLocations = BettingLocation::paginate();

        return view('admin.betting_location.index', compact('bettingLocations'));
    }

    public function create()
    {
        $bettingLocation = new BettingLocation();

        return view('admin.betting_location.create', compact('bettingLocation'));
    }

    public function store(CreateBettingLocationRequest $request)
    {
        BettingLocation::create($request->all());

        return redirect()->route('admin.betting-location.index')->with(['success' => trans('ui_admin.betting-location.messages.create-success')]);
    }

    public function edit($bettingLocationId)
    {
        $bettingLocation = BettingLocation::findOrFail($bettingLocationId);

        return view('admin.betting_location.edit', compact('bettingLocation'));
    }

    public function update(CreateBettingLocationRequest $request, $bettingLocationId)
    {
        $bettingLocation = BettingLocation::findOrFail($bettingLocationId);
        $bettingLocation->update($request->all());

        return redirect()->route('admin.betting-location.index')->with(['success' => trans('ui_admin.betting-location.messages.update-success')]);
    }

    public function destroy($bettingLocationId)
    {
        $bettingLocation = BettingLocation::findOrFail($bettingLocationId);
        $bettingLocation->delete();

        return back()->with(['success' => trans('ui_admin.betting-location.messages.delete-success')]);
    }
}

resources/views/admin/betting_location/create.blade.php
@extends('layouts.dashboard_admin.dashboard_template')

@section('content-header-title')
    {{ trans('ui.create') }}
@stop

@section('additionalInputs')

@stop

@section('content')
    @include('admin.betting_location.form', ['formRoute' => 'admin.betting-location.store', 'formMethod' => 'POST'])
@stop

resources/views/admin/betting_location/edit.blade.php
@extends('layouts.dashboard_admin.dashboard_template')

@section('content-header-title')
    {{ trans('ui.Edit') }}
@stop

@section('additionalInputs')

@stop

@section('content')
    @include('admin.betting_location.form', ['formRoute' => ['admin.betting-location.update', $bettingLocation->id], 'formMethod' => 'PUT'])
@stop

resources/views/admin/betting_location/form.blade.php
<div class="box box-success box-solid">
    <div class="box-header with-border">
        <h4 class="box-title"><strong>{{ trans('ui_admin.user.location-admin') }} {{ $bettingLocation->id? '"' . $bettingLocation->name .'"': '' }}</strong></h4>
    </div>
    {!! Form::model($bettingLocation, ['route' => $formRoute, 'method' => $formMethod]) !!}
    <div class="box-body" id="betting-location-form">
        <div class="row">
            <div class="col-lg-7 col-xs-12">
                <div class="box-body">
                    <div class="form-group">
                        {!! Form::label('name', trans('ui_admin.betting-location.fields.name')) !!}
                        {!! Form::text('name', $bettingLocation->name, ['class' => 'form-control', 'placeholder' => trans('ui_admin.betting-location.fields.name')]) !!}
                    </div>
                    <div class="form-group">
                        {!! Form::label('admin', trans('ui_admin.betting-location.fields.admin')) !!}
                        <v-select
                                label="name"
                                :placeholder="'{{ trans('ui_admin.user.location-admin') }}'"
                                :options="adminLocationUsers"
                                :filterable="true"
                                :clearable="false"
                                v-model="adminLocationUser"
                                @search="onSearchAdminLocationUsers"
                        ></v-select>
                        <input type="hidden" name="admin_user_id" v-model="adminLocationUser.id">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <button type="submit" class="btn btn-primary">{{ trans('ui.save') }}</button>
    </div>
    {!! Form::close() !!}
</div>

@section('js')
    <script>
        const vueAppBettingLocation = new Vue({
            el: '#betting-location-form',
            data: {
                adminLocationUsers:[],
                adminLocationUser:{!! $bettingLocation->adminLocation? json_encode($bettingLocation->adminLocation) : "{}" !!}
            },
            methods: {
                onSearchAdminLocationUsers: function (search, loading) {
                    this.fetchAdminLocationUsers(loading, search, this);
                },
                fetchAdminLocationUsers: _.debounce((loading, search, vm) => {
                    if(search) {
                        loading(true);
                        vm.$http.get('{{ route('api.admin.admin-location.index') }}' + '?search='+ search).then( response => {
                            vm.adminLocationUsers = response.data.data;
                            loading(false);
                        });
                    }

                }, 350),
            },
            mounted: function () {
            }
        });
    </script>
@append

resources/views/admin/betting_location/index.blade.php
@extends('layouts.dashboard_admin.dashboard_template')
<?php
    $AdminLTETableSorter = \AdminLTE\Laravel\Html\AdminLTETableSorter::create([
        'headings' => [
            ['name' => 'name', 'title' => trans('ui_admin.betting-location.fields.name')],
            ['title' => trans('ui.actions.singular'), 'sort' => false],
        ],
        'paginator' => $bettingLocations,
        'filters'   => true,
    ]);
?>
@section('filters')
    {{--<div class="col-xs-12 col-lg-2">--}}
        {{--<div class="form-group">--}}
            {{--{!! Form::label('project_id', trans('ui.tasks.fields.project')) !!}--}}
            {{--{!! Form::select('project_id', $projects->pluck('name', 'id'), request('project_id'), ['class' => 'form-control','placeholder' => trans('ui.select...')]); !!}--}}
        {{--</div>--}}
    {{--</div>--}}
@endsection

@section('content')

    <div class="row" id="user-index-page">
        <div class="col-xs-12">
            <div class="box box-success box-solid">

                <div class="box-header">
                    <h3 class="box-title">
                        <strong>
                            {{ trans('ui_admin.betting-location.plural') }} ({{ $bettingLocations->total() }})
                        </strong>
                    </h3>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row margin-bottom">
                        <div class="col-xs-12">
                            <a href="{{ route('admin.betting-location.create') }}" class="btn btn-primary">
                                <i class="fa fa-plus"></i>
                                {{ trans('ui.new') }}
                            </a>
                        </div>
                    </div>

                    <div class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover dataTable table-condensed" role="grid">
                                        <thead>
                                        {!! $AdminLTETableSorter->table() !!}
                                        </thead>
                                        <tbody>
                                        @foreach($bettingLocations as $location)
                                            <tr>
                                                <td>{{ $location->name }}</td>
                                                <td>
                                                    <a class="btn btn-info" href="{{route('admin.betting-location.edit', $location->id)}}">
                                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                                    </a>

                                                    <button type="button" class="btn btn-info"  @click="deleteTask({{$location->id}})">
                                                        {!! Form::model($location, ['route' => ['admin.betting-location.destroy', $location->id], 'method' => 'DELETE', 'ref'=>"delete-task-" . $location->id]) !!}
                                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                                                        {!! Form::close() !!}
                                                    </button>

                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    <div class="list-inline text-center">{!! $bettingLocations->appends(request()->all()) !!}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>

        <div class="v-cloak-loading" v-cloak>
            <modal :show-modal="deleteTaskModal.showModal">
                <h3 slot="header">Delete Task</h3>
                <p slot="body">Do you want to delete task?</p>
                <button slot="footer" class="btn btn-default" @click="deleteTaskModalOk">Ok</button>
                <button slot="footer" class="btn btn-default" @click="deleteTaskModalCancel">Cancel</button>
            </modal>
        </div>
    </div>
@stop

@section('js')
    <script>
        const vueApp = new Vue({
            el: '#content',
            data: {
                deleteTaskModal: {
                    showModal: false,
                    id: null,
                },
            },
            methods: {
                deleteTask: function (taskId) {
                    this.deleteTaskModal.id = taskId;
                    this.deleteTaskModal.showModal = true;
                },
                deleteTaskModalCancel:function () {
                    this.deleteTaskModal.showModal = false;
                },
                deleteTaskModalOk:function () {
                    const form = this.$refs['delete-task-' + this.deleteTaskModal.id];
                    form.submit();
                }
            },
            mounted: function () {
                $('#modal').on('hidden.bs.modal', () => {
                    this.deleteTaskModal.showModal = false;
                });
            }
        });
    </script>
@endsection