routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['prefix' => 'admin','middleware' => ['web', 'auth:admin']], function() {
    Route::get('/', function () {
        return view('admin.welcome');
    });

    Route::resource('betting-location', 'Admin\BettingLocationController', ['as' => 'admin']);
    Route::resource('user', 'Admin\UserController', ['as' => 'admin'] );
    Route::resource('player', 'Admin\PlayerController', ['as' => 'admin'] );
    Route::resource('lucky6/ticket', 'Admin\Lucky6TicketController', ['except' => ['destroy', 'edit', 'update'],'as' => 'admin.lucky6']);
    Route::get('lucky6/statistic', ['uses' => 'Admin\Lucky6TicketController@statistic','as' => 'admin.lucky6.statistic']);
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'player', 'middleware' => ['web', 'auth:web']], function() {

    Route::get('/', function () {
        return view('player.welcome');
    });

    Route::resource('lucky6/ticket', 'Player\Lucky6TicketController', ['as' => 'player.lucky6']);
});

resources/views/admin/lucky6/index.blade.php
@extends('layouts.dashboard_admin.dashboard_template')
<?php
    $AdminLTETableSorter = \AdminLTE\Laravel\Html\AdminLTETableSorter::create([
        'headings' => [
            ['name' => 'round_id', 'title' => trans('ui.lucky6.tickets.fields.round')],
            ['name' => 'created_at', 'title' => trans('ui.lucky6.tickets.fields.created_at')],
            ['name' => 'total_hits', 'title' => trans('ui.lucky6.tickets.fields.total-hits')],
            ['title' => trans('ui.actions.singular'), 'sort' => false],
        ],
        'paginator' => $lucky6Tickets,
        'filters'   => true,
    ]);
?>
@section('filters')
    <div class="col-xs-12 col-lg-2">
        <div class="form-group">
            {!! Form::label('date_from', trans('ui.lucky6.tickets.fields.date-from')) !!}
            {!! Form::text('date_from', request('date_from'), ['class' => 'form-control','placeholder' => trans('ui.select...'), 'id' => 'date-from-filter']); !!}
        </div>
    </div>
    <div class="col-xs-12 col-lg-2">
        <div class="form-group">
            {!! Form::label('date_to', trans('ui.lucky6.tickets.fields.date-to')) !!}
            {!! Form::text('date_to', request('date_to'), ['class' => 'form-control','placeholder' => trans('ui.select...'), 'id' => 'date-to-filter']); !!}
        </div>
    </div>
@endsection

@section('content')

    <div class="row" id="lucky6-index-page">
        <div class="col-xs-12">
            <div class="box box-success box-solid">

                <div class="box-header">
                    <h3 class="box-title">
                        <strong>
                            {{ trans('ui.lucky6.tickets.plural') }}
                        </strong>
                    </h3>
                </div>

                <!-- /.box-header -->
                <div class="box-body">

                    <div class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover dataTable table-condensed" role="grid">
                                        <thead>
                                        {!! $AdminLTETableSorter->table() !!}
                                        </thead>
                                        <tbody>
                                        @foreach($lucky6Tickets as $ticket)
                                            <tr>
                                                <td>{{ $ticket->lucky6_game_round_id }}</td>
                                                <td>{{ $ticket->created_at }}</td>
                                                <td>{{ $ticket->total_hits?? 'Not Play' }}</td>
                                                <td>
                                                    {{--<a class="btn btn-info" href="{{route('admin.player.edit', $user->id)}}">--}}
                                                        {{--<i class="fa fa-pencil" aria-hidden="true"></i>--}}
                                                    {{--</a>--}}

                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    <div class="list-inline text-center">{!! (get_class($lucky6Tickets) == 'Illuminate\Support\Collection') ? '':  $lucky6Tickets->appends(request()->all())!!}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
@stop

@section('js')
    <script src="{{ mix("/js/bootstrap-material-datetimepicker.js") }}" type="text/javascript"></script>

    <script>
        const vueApp = new Vue({
            el: '#lucky6-index-page',
            data: {
            },
            methods: {
            },
            mounted: function () {
                $('#date-to-filter').bootstrapMaterialDatePicker({time: false});
                $('#date-from-filter').bootstrapMaterialDatePicker({time: false}).on('change', function (e, date) {
                    $('#date-to-filter').bootstrapMaterialDatePicker('setMinDate', date);
                });
            }
        });
    </script>
@endsection

resources/views/admin/lucky6/statistic.blade.php
@extends('layouts.dashboard_admin.dashboard_template')

@section('filters')

    <div class="col-xs-12 col-lg-2">
        <div class="form-group">
            {!! Form::label('date_from', trans('ui.lucky6.tickets.fields.date-from')) !!}
            {!! Form::text('date_from', request('date_from'), ['class' => 'form-control','placeholder' => trans('ui.select...'), 'id' => 'date-from-filter']); !!}
        </div>
    </div>
    <div class="col-xs-12 col-lg-2">
        <div class="form-group">
            {!! Form::label('date_to', trans('ui.lucky6.tickets.fields.date-to')) !!}
            {!! Form::text('date_to', request('date_to'), ['class' => 'form-control','placeholder' => trans('ui.select...'), 'id' => 'date-to-filter']); !!}
        </div>
    </div>
@endsection

@section('content')

    <div class="row" id="lucky6-statistic-page">
        <div class="col-xs-12">
            <div class="box box-success box-solid">

                <div class="box-header">
                    <h3 class="box-title">
                        <strong>
                            {{ trans('ui.lucky6.tickets.statistic') }}
                        </strong>
                    </h3>
                </div>

                <!-- /.box-header -->
                <div class="box-body">
                    <div class="chart-container" style="position: relative; height:80vh;">
                        <canvas id="myChart"></canvas>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
@stop

@section('js')
    <script src="{{ mix("/js/Chart.js") }}" type="text/javascript"></script>

    <script>
        const vueApp = new Vue({
            el: '#lucky6-statistic-page',
            data: {
                data: {!! $ticketsStatistic->count() ? json_encode($ticketsStatistic->toArray()): json_encode([]) !!},
            },
            computed: {
                label: function () {
                    return Object.keys(this.data)
                },
                dataSet: function () {
                    let payment = {
                        label: '# of Payment',
                        data: [],
                        fillColor: 'rgba(255, 99, 132, 0.2)',
                        backgroundColor:'rgba(255, 99, 132, 0.2)',
                        borderColor: 'rgba(255, 99, 132, 0.2)',
                        borderWidth: 1
                    } ;

                    let payoff = {
                        label: '# of Payoff',
                        data: [],
                        backgroundColor: [
                            'rgba(54, 162, 235, 0.2)',
                        ],
                        borderColor: [
                            'rgba(54, 162, 235, 1)',
                        ],
                        borderWidth: 1
                    }

                    Object.keys(this.data).map(key => {
                        if(this.data[key].length == 1) {
                            payment.data.push(parseInt(this.data[key][0].payment));
                            payoff.data.push(parseInt(this.data[key][0].payoff))
                        } else {
                            let sum = this.data[key].reduce(function (total, value) {
                                total.payment = parseInt(total.payment) + parseInt(value.payment);
                                total.payoff  = parseInt(total.payoff) + parseInt(value.payoff);

                                return total
                            });

                            payment.data.push(parseInt(sum.payment));
                            payoff.data.push(parseInt(sum.payoff))
                        }
                    });

                    return [payment, payoff]
                }
            },
            methods: {
            },
            mounted: function () {
                var ctx = document.getElementById("myChart").getContext("2d");
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: this.label,
                        datasets: this.dataSet
                    },
                    options: {
                        responsive: true,
                        maintainAspectRatio: false,

                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });
            }
        });
    </script>



@endsection